name: net-delay-monitor-env
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pip
  - dash=2.10.*
  - dash-bootstrap-components=1.4.*
  # - dash-cytoscape==0.2.0
  - networkx=2.8.*
  - numpy=1.23.*
  - matplotlib=3.7.*
  - pandas=1.5.*
  - plotly=5.9.*
  - psycopg2=2.9.*
  - pyg=2.3.*
  - pytorch=2.0.*
  - pyyaml=6.*
  - torchaudio=2.0.*
  - torchvision=0.15.*
  # - kedro-datasets=1.4.2
  - pip:
    - torch-geometric-temporal