carrier: DAL

de_params:
  hr_shift: 4
  n_prev: 8
  n_pred: 2
  hr_curr: 12

model_name: GraphSAGE

model_params:
  n_layers: 2
  hidden_channels: 64
  aggr_func: mean
  dropout: 0.1
  optimizer_params:
    lr: 0.0001

start_time: 2023-02-01
end_time: 2023-06-01